### ISSUE TITLE
QR code password 

### ISSUE THREAD

**Issue by Browder96** [WormChickenWizard/hikvision-decrypter#3]
Hey, is it possible to get password from QR code on HikVision? Thanks!

**Comment by WormChickenWizard** [comment]
I'm not sure. This tool is strictly for decrypting the configuration file for certain hikvision cameras and clones of certain hikvision models for analysis.

**Comment by Browder96** [comment]
Oh I see. I would need something similar for RVI cams, but can't find anything :D
